### ISSUE TITLE
Check out Composer Manager in favor of Composer Autoload

### ISSUE THREAD

**Issue by cpliakas** [WhiteHouse/twitterapi#1]
Great module!

Just an FYI in case you are interested, [Composer Manager](https://drupal.org/project/composer_manager) could potentially be a better option than Composer Autoload since it would make this module compatible with other modules that use Guzzle by allowing them to use a single library space.

Just wanted to throw it out there in case you find it useful.

Thanks,
Chris

**Comment by bryanhirsch** [comment]
@cpliakas, thanks for the recommendation. We actually started with Composer Manager during initial development on [Tweet Server](https://github.com/whitehouse/tweetserver) and Twitter API, swapped it out for Composer Autoload while debugging something at some point, and then just never went back. For the minimum viable product Tweet Server, this did the trick. But Composer Manager could be helpful if the project grows or others are interested in taking Twitter API in other directions. We'll keep this in mind. In the meanwhile, pull requests are definitely welcome. :)

**Comment by cpliakas** [comment]
Sounds good. Thanks for the reply!
